This file works with vscode REST Client https://marketplace.visualstudio.com/items?itemName=humao.rest-client

### login authorized, get access token
POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "user@domain.com",
    "password": "12345678"
}

###################################################################
###################################################################
###################################################################

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidXNlckBkb21haW4uY29tIiwiaWF0IjoxNzQ2MjA5NzI4LCJleHAiOjE3NDYyMTAwMjh9.VKHBcxdSop3sU6NIJgqAoL_7KqEfCzBs2Yu6DiOdHGU
### create user
POST http://localhost:3000/users HTTP/1.1
content-type: application/json
Authorization: Bearer {{access_token}}

{
    "email": "user@domain.com",
    "password": "12345678",
    "phone": "+48 123 123 123"
}

### get all users
GET http://localhost:3000/users

### search user by id
GET http://localhost:3000/users/1

### search user by part of email
GET http://localhost:3000/users/search?email=domain.com

###################################################################
###################################################################
###################################################################

### get all managers
GET http://localhost:3000/managers

### create manager
POST http://localhost:3000/managers HTTP/1.1
content-type: application/json

{
    "email": "manager_john@domain.com",
    "password": "12345678",
    "firstName": "John",
    "lastName": "Doe"
}

###################################################################
###################################################################
###################################################################

### get all contractors
GET http://localhost:3000/contractors

### create contractor
POST http://localhost:3000/contractors HTTP/1.1
content-type: application/json

{
    "email": "company@contractor.com",
    "password": "12345678",
    "company": "WithInvoices"
}

### disable contractor

PATCH http://localhost:3000/contractors/1/can-login
Content-Type: application/json

{
    "canLogin": false
}

###################################################################
###################################################################
###################################################################

### get all invoices
GET http://localhost:3000/invoices

### search invoice by number
GET http://localhost:3000/invoices/search?number=FV/2024/001

### find invoices from last month
GET http://localhost:3000/invoices/last-month

### create invoice
POST http://localhost:3000/invoices
Content-Type: application/json

{
    "number": "FV/2024/001",
    "amount": 1000.12,
    "contractorId": 11
}