### get all managers
GET http://localhost:3000/managers

### create manager
POST http://localhost:3000/managers HTTP/1.1
content-type: application/json

{
    "email": "manager_john@domain.com",
    "password": "12345678",
    "firstName": "John",
    "lastName": "Doe"
}